---
- name: Déploiement de l'application web avec Nginx
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Créer le répertoire de destination
      file:
        path: /var/www/html/tp-app
        state: directory
        mode: '0755'

    - name: Copier les fichiers de l'application
      copy:
        src: app/
        dest: /var/www/html/tp-app/
        mode: '0644'

    - name: Copier la configuration Nginx depuis un template
      template:
        src: ansible/nginx_vhost.conf.j2
        dest: /etc/nginx/sites-available/tp-app.conf

    - name: Activer la configuration Nginx
      file:
        src: /etc/nginx/sites-available/tp-app.conf
        dest: /etc/nginx/sites-enabled/tp-app.conf
        state: link
        force: yes

    - name: Supprimer la configuration par défaut si elle existe
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted
